TRAIN:
  ENABLE: False
  DATASET: kinetics
  BATCH_SIZE: 2
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: False
  TPU_ENABLE: False
DATA:
  PATH_TO_DATA_DIR: /data1/hongn/kinetics-dataset/k400
  NUM_FRAMES: 8
  SAMPLING_RATE: 8
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  PATH_LABEL_SEPARATOR: ","
TIMESFORMER:
  ATTENTION_TYPE: 'divided_space_time'
SOLVER:
  BASE_LR: 0.005
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 11, 14]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
MODEL:
  MODEL_NAME: MOOSE
  NUM_CLASSES: 400
  ARCH: vit
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
  FUSION_MODE: space_only
  VISUAL_MODEL: dinov2
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 1
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 3
  CHECKPOINT_FILE_PATH: /data2/hongn/TimePSFormer/checkpoints/moose_space_only_dinov2/checkpoints/checkpoint_epoch_00008.pyth
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: /data2/hongn/TimePSFormer/checkpoints/
